### ISSUE TITLE
搜索结果跳转到某页后, 向上滑动, 效果是刷新搜索结果, 而非加载上一页

### ISSUE THREAD

**Issue by ironstress** [honjow/FEhViewer#10]
我个人的习惯是从上次看到的地方往前翻, 所以我建议"刷新搜索结果"只应该在搜索结果第一页的时候触发.

**Comment by honjow** [comment]
> 我个人的习惯是从上次看到的地方往前翻, 所以我建议"刷新搜索结果"只应该在搜索结果第一页的时候触发.

其实挺早之前我就想改了😂，只不过一直没想好怎么搞。现在这个逻辑确实有点反直觉

**Comment by honjow** [comment]
现在应该ok了
