### ISSUE TITLE
Feature请求，能不能加个在阅读页面时音量键控制翻页的功能？

### ISSUE THREAD

**Issue by VoidxHoshi** [honjow/FEhViewer#13]
这是个在阅读软件中非常常见的功能，请求添加，谢谢。

**Comment by honjow** [comment]
Android的应该可以做，iOS的话因为系统限制做不了

**Comment by honjow** [comment]
> 戳一下，因为这个功能实在是很方便。谢谢作者了。 （另外数据持久化组件是不是太多了？shared_preferences，get_storage，moor_flutter，hive，isar。仅仅作为建议）

shared_preferences 的话主要是iOS的要和原生那边共享一个控制的变量，这个要保留，其他的主要是遗留问题，后面应该只会保留hive，isar这两个
