### ISSUE TITLE
Win11 闪退

### ISSUE THREAD

**Issue by lsqzby** [honjow/FEhViewer#149]
在win11正式版安装后,使用clash进行全局代理，登录没有问题,线上收藏可以显示，但是在点开某些漫画后，整个应用闪退，后台也没了。请作者有时间的话，修复一下，谢谢。

**Comment by honjow** [comment]
windows进画廊闪退，以及更新tag翻译数据闪退，应该都是数据库bug。
大概和这个有关
https://github.com/isar/isar/issues/687
可能一下不是那么好处理

**Comment by honjow** [comment]
试试这个构建的版本。降低了数据库依赖版本。应该不会闪退了
https://github.com/honjow/FEhViewer/actions/runs/3304088238
