### ISSUE TITLE
Tag翻译数据的对应名称有些是markdown格式，不一定能正常渲染

### ISSUE THREAD

**Issue by VoidxHoshi** [honjow/FEhViewer#15]
插入图片Markdown语法代码：
```
![图片alt](图片链接 "图片title")
```
不写图片alt可能会渲染出错
写了会渲染不出来，因为渲染的是图片

如code geass
https://ehtt.vercel.app/edit/parody/code%20geass

**Comment by honjow** [comment]
其实这个原先就是是有处理的。不过前几天我也看到这个情况了。可能是正则没写好有些情况没匹配上。后面我修一下

**Comment by OpportunityLiu** [comment]
如果不想用正经的 MD Parser，为啥不直接用 ast 版本的数据库呢
