### ISSUE TITLE
“快速搜索”的导入导出失败

### ISSUE THREAD

**Issue by YOUQY979** [honjow/FEhViewer#150]
安卓10，“快速搜索”的导入导出功能：
导入的话，选择文件以后自动回到原界面，然后就没有反应了；
导出的话，会提示“Unable to download, please authorize first~”。
请问这是什么授权？我把所有的应用权限都设为允许了，仍然提示这个。

**Comment by YOUQY979** [comment]
我发现share功能可以正常导出txt文件，有办法可以把EhViewer导出的db文件导入进来吗？

**Comment by honjow** [comment]
什么手机什么系统。手头没有能测试的Android10设备，没法验证

**Comment by YOUQY979** [comment]
我更新到了v1.2.78+478.RC，导入正常了，导出还是显示“Unable to download, please authorize first”。
手机是小米mix2s，系统miui12.5.1稳定版，安卓版本10。
另：要是能像ehviewer那样导出所有数据（包括设置、快速搜索等）就太好了~
