### ISSUE TITLE
反馈：单张图片原图保存功能

### ISSUE THREAD

**Issue by s-stay-y** [honjow/FEhViewer#152]
无法保存图片到相册，无论是原图或者已加载的图片。
系统分享无法识别分选的是图片，识别分享的是文件，后续保存到文件中看不到后缀，把后缀改为jpg后可以识别正确图片。
希望添加
1.保存图片或原图可以保存到专用名称相册，便于管理
2.保存原图，无法查看进度。如果原图较大或者网络慢的话，不知道是否会保存失败，保存失败可否有一个列表可以一键重新加载保存
3.长按图片，中的重新加载和分享图片，可否直接添加保存图片，保存原图选项？

**Comment by honjow** [comment]
确实有点问题。这个可能要找时间重写下了。这部分是比较早期的代码。写得比较烂

**Comment by honjow** [comment]
新版已重写。保存现在应该正常了，原图的话加了个loading动画，但是暂时没有做缓存，如果重复保存会重复下载。
1的话可能比较麻烦，因为涉及到多平台，可能暂时不好做

**Comment by s-stay-y** [comment]
如果1不好做，可否有一个分享原图的选项，这样我可以利用分享这个功能用快捷指令把原图保存到对应相册

**Comment by s-stay-y** [comment]
刚刚测试，有分享原图功能，但只能保存到相册，无法将共享菜单中的图像保存到相册（我有一个很简单的快捷指令保存到对应相册）。分享原图按钮，似乎无法识别原图图像？我把分享的图像保存到文件发现是png格式。不知道是否因为原图是png，保存到相册自动转成jpg格式？这个原因导致分享原图无法通过快捷指令保存到指定相册
