### ISSUE TITLE
反馈：1.2.75版本保存原图及分享原图报错

### ISSUE THREAD

**Issue by s-stay-y** [honjow/FEhViewer#154]
报错如下
FileSystemException: Cannot create file, path = '/var/mobile/Containers/Data/Application/F0216D83-2444-4657-95BF-1637861D2D1/Library/Caches/ori_image_temp/2339191/1'
(OS Error: Is a directory, errno = 21)

**Comment by honjow** [comment]
先试试清缓存再操作，新版大概解决了。
