### ISSUE TITLE
老哥，能否添加支持ios13安装啊

### ISSUE THREAD

**Issue by kevinxluo** [honjow/FEhViewer#16]
如题，感谢老哥

**Comment by kevinxluo** [comment]
已解决，下旧版可以

**Comment by honjow** [comment]
理论上我是没有做限制的，但是后面几个版本我改用脚本打包ipa了。可能导致有点问题，你是用sideloadly装的吗

**Comment by kevinxluo** [comment]
> 理论上我是没有做限制的，但是后面几个版本我改用脚本打包ipa了。可能导致有点问题，你是用sideloadly装的吗

对，用sideloadly试过，还用爱思助手试过，爱思助手提示说文件已损坏，我上网查了说可能是因为打包方式不同，ios13不识别这个
![image](https://user-images.githubusercontent.com/84461294/132823835-bba6416d-2069-4af9-aa1f-49987e033026.png)
![image](https://user-images.githubusercontent.com/84461294/132824003-fa4d5ca2-a735-40ed-bd1e-269e8c5f132c.png)
294及之前的版本ios13安装没问题，298和302两个新版本有这个问题

**Comment by kevinxluo** [comment]
Checking iOS version...
iOS version 13.1.3, will not mangle bundleID
ERROR: Guru Meditation b4822c@2364:8a63ba Can't listdir a file
