### ISSUE TITLE
Gallery lists have 25 max posts limit :')

### ISSUE THREAD

**Issue by KiraiEEE** [honjow/FEhViewer#167]
in the older versions (1.2.77 as latest of the there is no limit :')  and works fine

here per exp of the issue :
![Screenshot_2022-11-06-16-58-28-731_com.honjow.fehviewer-picsay.jpg](https://user-images.githubusercontent.com/54278089/200181731-d417a0e3-9f6c-48dc-8e8a-7090671ab883.jpg)

thx for reading hope u fix it 

arigato 🌸

**Comment by honjow** [comment]
#166 
If you don't use exh, use a version where the tag doesn't end in EX

**Comment by KiraiEEE** [comment]
> #166 
> If you don't use exh, use a version where the tag doesn't end in EX

yep at version 1.2.77 there is no issue 🌸
