### ISSUE TITLE
作者或许可以考虑，将提醒vpn用户的重要信息写在README中。

### ISSUE THREAD

**Issue by YJ2CS** [honjow/FEhViewer#192]
使用的Android版本，用了半个月，今天才发现这一点。

如果正在使用vpn（clash for Android），“设置-高级-代理”中，应当选择为“直连”，并且关闭“域名前置”。

与之相对的是，如果代理填写为本地端口（如下），效果会非常差，经常遇到图片加载不出来。
```text
http代理
127.0.0.1
7890
```

更改为“直连”后，问题解决。

**Comment by honjow** [comment]
@YJ2CS 不太考虑
