### ISSUE TITLE
申请功能

### ISSUE THREAD

**Issue by xiaozixun** [honjow/FEhViewer#21]
希望能添加“阅读时屏幕常亮”“启动时输入密码或滑屏解锁”和“快捷搜索自定义名称”几个功能
还有就是开启“纯黑”后并不是全为黑色，这是bug吗？
![Screenshot_20211107_212441_com honjow fehviewer](https://user-images.githubusercontent.com/22409452/140648193-117b137d-85bf-4e22-8ca1-f7fe51f90bf9.jpg)

此外还有使用搜索时搜索栏里必须输入文字，无法单独使用高级搜索。

**Comment by honjow** [comment]
启动密码锁功能只要你在设置-安全 开启了自动锁定默认启动就会锁定的
快捷搜索也是早就有了的，就在搜索边栏，按+就能保存当前搜索词
想单纯使用高级搜索的筛选功能的话，直接在画廊页看就行，两边共用筛选配置的，所以画廊页才会同样设置筛选入口。设置好下拉刷新一下就行了
主题的纯黑主要是底色的设置，想设置项这样的不会变成纯黑，画廊列表和画廊页这样的地方就会有比较明显的区别

**Comment by honjow** [comment]
常亮开关目前确实没有，只有在启用自动翻页的时候默认常亮，后面我再加吧

**Comment by xiaozixun** [comment]
> 
> 
> 启动密码锁功能只要你在设置-安全 开启了自动锁定默认启动就会锁定的 快捷搜索也是早就有了的，就在搜索边栏，按+就能保存当前搜索词 想单纯使用高级搜索的筛选功能的话，直接在画廊页看就行，两边共用筛选配置的，所以画廊页才会同样设置筛选入口。设置好下拉刷新一下就行了 主题的纯黑主要是底色的设置，想设置项这样的不会变成纯黑，画廊列表和画廊页这样的地方就会有比较明显的区别

密码锁是想要来单手滑动九宫格解锁，开它也只是为了误触时不会显示；
自定义这个是如果以“language:chinese female:"females only misc:full censorship”这样添加的时候太长了，能简短点就好了；
原来是这样，只是如果这样筛选的话，在想看更新的本子还得再次重新改回来（单手不太能操作的过来），所以想着能不能加个快捷搜索；
原来是这样的考虑，我还以为是bug。

**Comment by xiaozixun** [comment]
> 常亮开关目前确实没有，只有在启用自动翻页的时候默认常亮，后面我再加吧

新发现些问题和功能申请：
问题：发送评论会回复两次以上；在阅读时只能通过按钮来跳转页码，而不能通过点击进度条跳转。
功能申请：预览页码的跳页功能和阅读时的页面缩放功能。
还有一个不算问题的小问题：下拉刷新拉得太远了。

提了这么多实在是抱歉，希望大佬不要烦我。😁

**Comment by xiaozixun** [comment]
> 常亮开关目前确实没有，只有在启用自动翻页的时候默认常亮，后面我再加吧

用了这段时间来有几个设置成“瀑布流-大”后右下角显示页数的有时会不清楚（主要是图片颜色为亮色时）；还有就是浏览画廊的时候的“阅读设置”能不能改成弹出形式（主要是在阅读时单手操作不便）？
最后就是改成ex后网络实在感人，有没有办法解决下。
