### ISSUE TITLE
下载的归档可以直接在APP里阅读吗？

### ISSUE THREAD

**Issue by suraxiuxiu** [honjow/FEhViewer#22]
很喜欢归档下载这个功能  这样大量下载漫画也不会消耗配额  先谢谢大佬
但APP里点击下载好的归档没有反应 点封面会跳转漫画详情页  是不支持直接阅读归档吗？

**Comment by Atomseek** [comment]
这个归档跟下载的区别是什么？我看了一下貌似只是下载成压缩包。还有能不能设置归档目录？在data内找出来有点麻烦。
另外压缩包适合放nas里，用Lanraragi管理很方便。

**Comment by Mapaler** [comment]
最好是能用Archive下载的在后台解压后替换普通下载的直接阅读，对于有H@H的来说就不用担心动不动就被封IP了。

**Comment by Mapaler** [comment]
直接阅读下载的归档是比较实用的功能。希望作者能把这个加入开发。

归档下载后，第一次打开时再触发解压即可。
普通下载下个几千张就被封IP了。

**Comment by honjow** [comment]
已经完成部分
