### ISSUE TITLE
安卓6.01平板阅读ui排版存在错版

### ISSUE THREAD

**Issue by ffbi** [honjow/FEhViewer#221]
我用安卓6.0.1的平板在竖版使用APP时 阅读胶囊框会错版 导致无法点击阅读键

**Comment by ffbi** [comment]
![Uploading 16719449827401046850000988755224.jpg…]()

**Comment by ffbi** [comment]
必须把平板横过来 横屏状态下才能解决 而且这个排版错误不是所有的本子都有 有些有，有些没有

**Comment by ffbi** [comment]
有的时候即使横屏过来也无法重新排版让胶囊归位

**Comment by ffbi** [comment]
![Uploading 16719451227471213068347665873574.jpg…]()

**Comment by ffbi** [comment]
请开发者大大务必解决一下这个问题 这样就没法阅读一些本子，很难受😭

**Comment by ffbi** [comment]
哦哦 发现横屏状态下可以通过拖动中间的调节条来让排版复位 但是竖屏状态下调节条不可用 还是需要把屏幕横过来才可以,.,还请大大优化下竖屏调节的功能

**Comment by honjow** [comment]
明显是字号太大了。ui方面我只能保证使用标准大小字体的情况，大字号出现排版问题没办法解决
