### ISSUE TITLE
功能问题 建议

### ISSUE THREAD

**Issue by ghost** [honjow/FEhViewer#23]
平板模式下底栏顶栏阴影有问题
绕过SNI阻断和代理同时开启会无法加载
建议加入阅读器记住双页显示 全屏功能
建议加入类似[Ehviewer](https://gitlab.com/NekoInverter/EhViewer)的本地屏蔽功能
~~建议加入手动设置图片预加载数量~~ 找到了

**Comment by honjow** [comment]
第一个问题确实有。但是这个貌似和用的过渡动画以及和上下bar的高斯模糊有关系，我试过解决但是没成功
第二个问题的话使用的代理是什么工具呢，后面我验证一下
记住双页这个目前只是会单独给修改过的画廊设置，我后面加几个预设值的选择吧
全屏的话可能你用的是Android平台，因为在设置阅读页全屏的时候，在进入和返回时出现布局抖动的问题，比较影响，所以Android上的阅读页我保留了状态栏
本地屏蔽可以做，但是如果是做tag相关的屏蔽的话，在请求画廊列表时，需要给额外发api请求，获取到完整的tag信息，才能屏蔽。这样一来会导致列表请求慢一些

**Comment by CrazyFox24955** [comment]
> 第一个问题确实有。但是这个貌似和用的过渡动画以及和上下bar的高斯模糊有关系，我试过解决但是没成功 第二个问题的话使用的代理是什么工具呢，后面我验证一下 记住双页这个目前只是会单独给修改过的画廊设置，我后面加几个预设值的选择吧 全屏的话可能你用的是Android平台，因为在设置阅读页全屏的时候，在进入和返回时出现布局抖动的问题，比较影响，所以Android上的阅读页我保留了状态栏 本地屏蔽可以做，但是如果是做tag相关的屏蔽的话，在请求画廊列表时，需要给额外发api请求，获取到完整的tag信息，才能屏蔽。这样一来会导致列表请求慢一些

代理使用[XTLS/AnXray](https://github.com/XTLS/AnXray) vmess节点 路由默认配置全开 内核设置开启流量探测以及解析目标地址

**Comment by CrazyFox24955** [comment]
对了，有空的话能不能把载图动画换一个 ~~好丑~~💧

**Comment by honjow** [comment]
> 对了，有空的话能不能把载图动画换一个 ~~好丑~~💧

不换🌚

**Comment by CrazyFox55673** [comment]
> > 对了，有空的话能不能把载图动画换一个 ~好丑~💧
> 
> 不换🌚

不开New Issues了 在安卓设备上内存泄露严重 10分钟即可达到600MB 仅打开app放着不动也会泄露
