### ISSUE TITLE
一些收藏的画廊无法观看和下载，但在pc上是可以看的

### ISSUE THREAD

**Issue by hentaisama** [honjow/FEhViewer#26]
![7C78ED37-110A-4FED-A8C8-097ED307B8E9](https://user-images.githubusercontent.com/37970748/148441734-9e49170c-08c1-4be7-83cd-4d4dba04b7a3.jpeg)
希望可以解决一下这个问题，谢谢啦

**Comment by honjow** [comment]
你先弄明白这是啥情况吧
