### ISSUE TITLE
搜索高级选项打开显示删除的画廊会少很多画廊

### ISSUE THREAD

**Issue by FelexTriz** [honjow/FEhViewer#262]
但是软件非常好👍，比epanda好多了

**Comment by honjow** [comment]
@FelexTriz eh之前网站搜索引擎更新过。显示删除画廊现在的意思是仅显示删除画廊

**Comment by FelexTriz** [comment]
我也感觉是这样，感谢回答，请关闭吧😚

**Comment by gnlhazsmlgjc** [comment]
> 但是软件非常好👍，比epanda好多了

请问你是怎么使用VPN的呢？我在使用FEH时非常的卡顿，直接从浏览器里进入却是正常的
