### ISSUE TITLE
cookies登录，从剪贴板读取怎么使用？

### ISSUE THREAD

**Issue by Mapaler** [honjow/FEhViewer#40]
我使用 document.cookie 获取到的字符串，没有任何反应
`ipb_member_id=xxxxxxxx; ipb_pass_hash=xxxxxxxxxxxxxxxxxxxxxxxxxxxx; igneous=xxxxxxxxxxxxxxx; sk=xxxxxxxxxxxxxxxxxxxxxx; hath_perks=xxxxxxxxxxxxxxxxxxxxxxx`
替换成&符号也没反应
`ipb_member_id=xxxxxxxx&ipb_pass_hash=xxxxxxxxxxxxxxxxxxxxxxxxxxxx&igneous=xxxxxxxxxxxxxxx&sk=xxxxxxxxxxxxxxxxxxxxxx&hath_perks=xxxxxxxxxxxxxxxxxxxxxxx`

**Comment by honjow** [comment]
前面的版本更新的新的解析方式。你用最新版看下现在这两种形式能解析了没

**Comment by Mapaler** [comment]
刚才装了 [feh-v1.2.20+380-arm64-v8a-release.apk](https://github.com/honjow/FEhViewer/releases/download/1.2.20%2B380/feh-v1.2.20+380-arm64-v8a-release.apk) 试了，还是无法从剪贴板读取，点了没反应。

手动粘贴可以看到剪贴板是有内容的
![Screenshot_20220317-191448](https://user-images.githubusercontent.com/6565860/158797789-8bd45299-7ee7-47d3-9005-6abf3eb7e19c.png)

**Comment by honjow** [comment]
> 刚才装了 [feh-v1.2.20+380-arm64-v8a-release.apk](https://github.com/honjow/FEhViewer/releases/download/1.2.20%2B380/feh-v1.2.20+380-arm64-v8a-release.apk) 试了，还是无法从剪贴板读取，点了没反应。
> 
> 手动粘贴可以看到剪贴板是有内容的 ![Screenshot_20220317-191448](https://user-images.githubusercontent.com/6565860/158797789-8bd45299-7ee7-47d3-9005-6abf3eb7e19c.png)

现在的版本应该好了

**Comment by Mapaler** [comment]
成功了
