### ISSUE TITLE
无法正常显示自己的评分和收藏

### ISSUE THREAD

**Issue by jiut** [honjow/FEhViewer#41]
评分后，退出页面就无法看到自己的评分，但是在浏览器中访问画廊可以看到已经有评分了。退出应用后重进也没用，只能清除缓存，有时候清除缓存也没有用。收藏的显示也有这样的问题。

站点：e-hentai
环境：iOS
版本：1.2.14（375）

**Comment by honjow** [comment]
下拉画廊刷新一下呢

**Comment by jiut** [comment]
> 下拉画廊刷新一下呢

其实在画廊页面评完分还能正常显示，出去之后就没了，刷新也没用。收藏之后退出页面能正常显示，不过刷新就没了，再次进入页面也会显示。

**Comment by jiut** [comment]
录屏我上传到B站了，在审核。

**Comment by jiut** [comment]
收藏夹的命名（比如将Favorite 0改成“默认收藏夹”，Favorite 1改成“无H收藏夹”）和收藏内容也会出现类似的问题。

**Comment by jiut** [comment]
现在还是有类似问题![image](https://user-images.githubusercontent.com/52725935/189636990-275ba0e3-3b92-4b3a-ab49-2a473e813769.png)

**Comment by jiut** [comment]
上面两个明明在收藏夹中，却不能正常显示图标。
