### ISSUE TITLE
安卓12 MIUI13下载图片提示错误IMAGE 509

### ISSUE THREAD

**Issue by poiulkjmn** [honjow/FEhViewer#53]
![Screenshot_2022-03-30-22-33-29-796-edit_com.honjow.fehviewer.jpg](https://user-images.githubusercontent.com/33369208/160860132-2b0586fa-22d5-4328-a20e-39fbef073359.jpg)

**Comment by poiulkjmn** [comment]
![Screenshot_2022-03-30-22-33-29-796-edit_com.honjow.fehviewer.jpg](https://user-images.githubusercontent.com/33369208/160860434-c1e1640a-a0d2-4a43-9fbe-e9986670ae7a.jpg)

**Comment by honjow** [comment]
509是你的下载配额不够了 参考 [http://www.ehviewer.com/help#509](url)

**Comment by poiulkjmn** [comment]
> 509是你的下载配额不够了 参考 [http://www.ehviewer.com/help#509](url)

![Screenshot_2022-03-31-09-21-57-830-edit_com.android.browser.jpg](https://user-images.githubusercontent.com/33369208/160957373-476b0d96-3d86-41eb-b846-4c65ad4cd924.jpg)
是我的代理问题

**Comment by poiulkjmn** [comment]
> 509是你的下载配额不够了 参考 [http://www.ehviewer.com/help#509](url)
在不更换代理的情况下，有没有其他的方法解决问题
