### ISSUE TITLE
没有以图搜图功能吗?很想要.希望添加.

### ISSUE THREAD

**Issue by a810357411** [honjow/FEhViewer#55]
希望添加图片搜索功能

**Comment by OYcedar** [comment]
eh本身就没这个功能吧

**Comment by a810357411** [comment]
> eh本身就没这个功能吧

有啊.
![微信图片_20220407135755](https://user-images.githubusercontent.com/102864136/162130411-0a7e7def-9aad-4ff4-9cd9-774c407e8128.jpg)
![微信图片_20220407135803](https://user-images.githubusercontent.com/102864136/162130432-94cd53c7-a208-475b-96d2-87ac815ba2d4.jpg)

**Comment by a810357411** [comment]
> eh本身就没这个功能吧

有吧
![微信图片_20220407135755](https://user-images.githubusercontent.com/102864136/162130668-797fcc31-9588-4680-bc46-8fc1dfda87d0.jpg)
![微信图片_20220407135803](https://user-images.githubusercontent.com/102864136/162130681-651b47a4-efc9-4a82-afdb-f56e55e0fb10.jpg)
