### ISSUE TITLE
immersive mode

### ISSUE THREAD

**Issue by 06041989** [honjow/FEhViewer#56]
Could there be an option of immersive mode in general, or specifically while reading? When reading vertically, the status bar and navigation bar is annoying. Bellow is an example where status bar and the navigation bar are visible.
![Screenshot_20220408-150504](https://user-images.githubusercontent.com/93400100/162508838-e8b2b34f-81a1-453b-a0fd-9f41d341126e.png)

**Comment by honjow** [comment]
[completed](https://github.com/honjow/FEhViewer/commit/ec04984a22758ca90212b2a441a66e37a56bf42d)
