### ISSUE TITLE
Api.getMoreGalleryInfo(tuple.item1, refresh: true) seems to have no effect, redundant

### ISSUE THREAD

**Issue by tenSunFree** [honjow/FEhViewer#6]
Api.getMoreGalleryInfo(tuple.item1, refresh: true) seems to have no effect, redundant

<img width="480" alt="2021-06-27_020150" src="https://user-images.githubusercontent.com/23090085/123521869-eb673400-d6eb-11eb-9240-23be407f5c2a.png">

<img width="460" alt="2021-06-27_020235" src="https://user-images.githubusercontent.com/23090085/123521877-f326d880-d6eb-11eb-8697-621565b29e1b.png">

**Comment by honjow** [comment]
This is related to the initial design
Now it does seem a little redundant
However, when the Japanese title is not turned on in the website settings, this request can get the Japanese title if it is turned on in the application settings
