### ISSUE TITLE
我用的vpn打开结果提示ip被ban了6小时是怎么回事

### ISSUE THREAD

**Issue by ludenswww** [honjow/FEhViewer#64]

**Comment by lukemin** [comment]
你用公共vpn或鸡场的节点的话，别人也用相同的节点访问，后者你下载浏览速度太快就会认为你在爬连接，被封禁。

**Comment by sichuanqianwan** [comment]
可以告诉我你的连接方式吗？我的速度大概是一小时几张图片，预览都加载不出来，但是墙外所有软件都可以流畅运行，让我实在无能为力> 你用公共vpn或鸡场的节点的话，别人也用相同的节点访问，后者你下载浏览速度太快就会认为你在爬连接，被封禁。

**Comment by lukemin** [comment]
我用app可以直连，不用代理

**Comment by ludenswww** [comment]
> 

你是怎么做到的，我只有开梯子才能上，不用的话就什么都加载不出来，显示ip被ban了

**Comment by lukemin** [comment]
> > 
> 
> 你是怎么做到的，我只有开梯子才能上，不用的话就什么都加载不出来，显示ip被ban了

建议你使用以下 ehviewer
