### ISSUE TITLE
Flutter run error: Could not complete submission of dSYM

### ISSUE THREAD

**Issue by coda1997** [honjow/FEhViewer#7]
I meet this issue when I am trying running the code to deploy in my iPhone.

Here is the detail info:

Project /Users/dadachen/workspace/FEhViewer built and packaged successfully.
    Uploading dsym file
    error: Could not complete submission of dSYM at
    /Users/dadachen/workspace/FEhViewer/build/ios/Debug-iphoneos/fehviewer.app.d
    SYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=2 "File
    no longer exists at (null)" UserInfo={NSLocalizedFailureReason=File no
    longer exists at (null)}
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Could not build the precompiled application for the device.

---
I do not have any ideas of that. Could you give me a help?

**Comment by coda1997** [comment]
I have replaced the google firebase plist with mine. So can I do something to solve this?

**Comment by honjow** [comment]
You can try to configure Runner.xcodeproj in xcode. left click on TARGETS, Runner, right select `Build Phases` ,
expand `Run Script`, 
comment out this line
`"${PODS_ROOT}/FirebaseCrashlytics/upload-symbols" -gsp ${GOOGLESERVICE_INFO_LOCATION} -p ios "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_ FILE_NAME}"`

There may be something wrong with this script, I'll try to fix it

**Comment by coda1997** [comment]
It works for me. Thank you so much! ☺️
