### ISSUE TITLE
cdn.jsdelivr.net已被DNS污染

### ISSUE THREAD

**Issue by VoidxHoshi** [honjow/FEhViewer#73]
如题，所以用这个下载tag数据会有问题。

**Comment by honjow** [comment]
🌚还有没有好使的cdn

**Comment by rootmelo92118** [comment]
> 🌚还有没有好使的cdn

放gitlab上是好選擇

**Comment by honjow** [comment]
> > 🌚还有没有好使的cdn
> 
> 放gitlab上是好選擇

tag数据在哪我又不能控制。是别的项目

**Comment by rootmelo92118** [comment]
> 

Tag的數據時常更動嗎？

**Comment by rootmelo92118** [comment]
> > > 🌚还有没有好使的cdn
> > 
> > 
> > 放gitlab上是好選擇
> 
> tag数据在哪我又不能控制。是别的项目

[https://fastly.jsdelivr.net/gh/EhTagTranslation/DatabaseReleases/db.raw.json.gz](https://fastly.jsdelivr.net/gh/EhTagTranslation/DatabaseReleases/db.raw.json.gz)

這是我在網路紹看到別人的解決方案，目前被牆的只是cdn.jsdelivr.net，並非整個*.jsdelivr.net，換成fastly應該可以暫時解決問題

測試結果如下：
[https://www.boce.com/http/d94e9c332c4174f64392025713cb746b.html](https://www.boce.com/http/d94e9c332c4174f64392025713cb746b.html)
雖然部分省份延遲偏高，但依然可以連上。
