### ISSUE TITLE
搜索高级选项能不能加上最低评分几星的选项？

### ISSUE THREAD

**Issue by lukemin** [honjow/FEhViewer#9]
搜索高级选项能不能加上最低评分几星的选项？

**Comment by honjow** [comment]
😅这个一直都有啊。。。用手往上拉一下

**Comment by lukemin** [comment]
第一次使用不太懂，的确是比ehviewer漂亮，但是不知道什么原因，同样的网络环境下， nekolnverter的ehviewer秒加载，而Fehviewer要转很多圈才勉强加载，加载的时候速度大约是ehviewer的十分之一，而且还会出现 dioerrortype...的提示。

**Comment by honjow** [comment]
> 第一次使用不太懂，的确是比ehviewer漂亮，但是不知道什么原因，同样的网络环境下， nekolnverter的ehviewer秒加载，而Fehviewer要转很多圈才勉强加载，加载的时候速度大约是ehviewer的十分之一，而且还会出现 dioerrortype...的提示。
> 设置高级选项里面开启了 **_域名前置_**，没有使用自定义hosts

是指ex吗？里站确实一直有连接问题，我一直搞不懂啥原因。所以导致我平时都不看ex了

**Comment by lukemin** [comment]
是的，你可以参考一下nekolnverter的代码，他也开源了。https://gitlab.com/NekoInverter/EhViewer

**Comment by honjow** [comment]
> 是的，你可以参考一下nekolnverter的代码，他也开源了。https://gitlab.com/NekoInverter/EhViewer

参考不了，我这是flutter写的。。

**Comment by lukemin** [comment]
他网络的设置部分可以借鉴一下。

**Comment by honjow** [comment]
> 他网络的设置部分可以借鉴一下。

没有办法。从底层开始的http请求实现都不一样。而且ehviewer用的okhttp，不能指望flutter有okhttp这东西。
正常来说里站表站的解析处理除了访问的域名不同，其他都是一样的。一般不会有谁单独给里站做啥处理。
除非我重写整个网络层，全改成在原生层用okhttp请求，但这不现实，我也做不到

**Comment by lukemin** [comment]
ehviewer 选项里面他有一个内置hosts.txt，我想这个应该是最主要的，我把此选项打开了，所以ehviewer速度快

**Comment by lukemin** [comment]
public class EhDns implements Dns {

    private static final Map<String, List<InetAddress>> builtInHosts;

    static {
        Map<String, List<InetAddress>> map = new HashMap<>();
        if (Settings.getBuiltInHosts()){
            put(map, "e-hentai.org", "104.20.135.21+104.20.134.21");
            put(map, "repo.e-hentai.org", "94.100.24.77+94.100.24.78+94.100.24.79");
            put(map, "upload.e-hentai.org", "94.100.24.81+94.100.24.71");
            put(map, "forums.e-hentai.org", "94.100.18.243");
            put(map, "ehgt.org", "37.48.89.44+81.171.10.48");
            put(map, "ul.ehgt.org", "94.100.24.82+94.100.24.72");
        }

        if (Settings.getBuiltEXHosts()){
            put(map, "exhentai.org", "178.175.128.254+178.175.128.252+178.175.129.252+178.175.129.254+178.175.132.20+178.175.132.22");
        }

        builtInHosts = map;
    }

    private final Hosts hosts;
    private static DnsOverHttps dnsOverHttps;

**Comment by honjow** [comment]
> eh的域名对应着好几个ip，但是Fehviewer相同域名只能添加其中的一个，不能重复添加。详见次链接
> Ehviewer_CN_SXJ的
> https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/app/src/main/java/com/hippo/ehviewer/client/EhDns.java
> 
> NekoInverter/EhViewer的
> ```java
>     static {
>         Map<String, List<InetAddress>> map = new HashMap<>();
>         put(map, "e-hentai.org", "104.20.26.25", "104.20.26.25");
>         put(map, "e-hentai.org", "104.20.134.21", "104.20.135.21", "172.67.0.127");
>         put(map, "exhentai.org", "178.175.128.252", "178.175.129.252", "178.175.129.254", "178.175.128.254",
>                 "178.175.132.20", "178.175.132.22");
>         put(map, "repo.e-hentai.org", "94.100.28.57", "94.100.29.73");
> ```
> 官网链接
> https://ehwiki.org/wiki/IPs

和这个关系不大，不用域前置，只用梯子，里站访问也是不理想

**Comment by lukemin** [comment]
我现在NekoInverter/EhViewer，开启内置hosts.txt以及域名前置联通4G打开ex秒开，图片分辨率设置为自动，预下载后面5张图片。
