### ISSUE TITLE
Feature請求，自動翻頁(幻燈片)閱讀

### ISSUE THREAD

**Issue by buffalobill-taiwan** [honjow/FEhViewer#94]
有時兩手都沒空

**Comment by honjow** [comment]
😢点一下那个沙漏图标

**Comment by buffalobill-taiwan** [comment]
感謝，那page animations可以關掉嗎？目前只有選項「Tap to turn page animations」沒有針對Auto的...

**Comment by honjow** [comment]
> 感謝，那page animations可以關掉嗎？目前只有選項「Tap to turn page animations」沒有針對Auto的...

我打算把那个开关统一成翻页动画，不再区分手动和自动，等更新吧
