### ISSUE TITLE
关于分组功能建议

### ISSUE THREAD

**Issue by HanamiZzh** [honjow/FEhViewer#96]
分组一般用来存一些自己常用的作者之类的，我有两台设备，由于无法导入导出，导致分组要来回重复添加。希望分组也可以和快速搜索一样可以导出吧。虽然有快速搜索功能，但确实还是分组更加直观快捷一点。
另：非常感谢作者对软件的开发！

**Comment by honjow** [comment]
多台设备的话，更推荐直接用webdav的同步功能。目前webdav可以同步的有：历史记录，阅读进度，分组配置（要手动点上面的按钮），快速搜索（貌似目前有点问题）
导入导出功能也会考虑做，但可能不会那么快

**Comment by HanamiZzh** [comment]
好的 非常感谢回复！

**Comment by BunnySakura** [comment]
> 多台设备的话，更推荐直接用webdav的同步功能。目前webdav可以同步的有：历史记录，阅读进度，分组配置（要手动点上面的按钮），快速搜索（貌似目前有点问题） 导入导出功能也会考虑做，但可能不会那么快

我想另外提一个建议，分组功能目前貌似是根据设置的标签，全部符合才显示。我希望加一个开关，实现符合某个标签就显示。就是把`&&`替换成`||`,`AND`->`OR`。

**Comment by honjow** [comment]
分组的本质是用的网站的搜索功能。你没用过网站的搜索吗？
你以为是我不想支持？

**Comment by BunnySakura** [comment]
> 分组的本质是用的网站的搜索功能。你没用过网站的搜索吗？ 你以为是我不想支持？

擦，还以为是实现了一个类似订阅的功能呢，行吧，还是感谢大佬造软件了🤣🤣🤣
